version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # Change localhost to kafka when running services in container
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: iot_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - kafka-net

  # producer-service:
  #   build: ./producer-service
  #   depends_on:
  #     - kafka
  #   networks:
  #     - kafka-net

  # consumer-service:
  #   build: ./consumer-service
  #   depends_on:
  #     - kafka
  #     - postgres
  #   networks:
  #     - kafka-net

  # api-gateway:
  #   build: ./api-gateway
  #   depends_on:
  #     - postgres
  #   networks:
  #     - kafka-net
  #   ports:
  #     - "8080:8080"

networks:
  kafka-net:
    driver: bridge
